<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textField_Password</name>
   <tag></tag>
   <elementGuidId>ad9f7479-1b83-4b6a-80e1-6ba268373738</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a0e1112-df8b-49d1-b17c-6d19304069bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8772e09b-8a11-4ab1-911b-fc06b233062f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d9f48bfb-4d9a-4f7c-8b15-d5b7bfa17a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter text</value>
      <webElementGuid>3de022ff-693d-4916-afcf-6064ffa37702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>52003f81-d93e-494b-954e-08976572f5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f186ba3d-fcf3-4b71-9707-0d9583d0c08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;animated fadeIn&quot;]/div[@class=&quot;cover cover-basic cover-light sc-login-wrapper d-lg-block d-none&quot;]/div[@class=&quot;cover-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;cover-content mw-md-500px&quot;]/div[@class=&quot;form-wrapper&quot;]/div[@id=&quot;login&quot;]/form[1]/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group col-12&quot;]/div[@class=&quot;field field-underline
        light
        field-floating
        
        field-password&quot;]/div[@class=&quot;form-control-wrapper&quot;]/input[@id=&quot;password&quot;]</value>
      <webElementGuid>4b643022-65ad-4861-84f5-44a009c64db6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password']</value>
      <webElementGuid>86e5c8de-1c61-41f2-a0c2-d251b7c88e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login']/form/div/div[2]/div/div/input</value>
      <webElementGuid>1a16e2fa-88ee-46fa-97e8-e74ef542f39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>14a76695-e386-47ca-8438-fb0e8b3359ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @id = 'password' and @placeholder = 'Enter text' and @type = 'password']</value>
      <webElementGuid>6e1900dc-f08f-4f2e-badb-b965f78abf43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
